---
# tasks file for docker_role
- name: Copy of docker install script
  template:
    src: "docker_install.sh.j2"
    dest: "/home/{{ ansible_user }}/docker_install.sh"

- name: Run docker install script
  command: sh /home/{{ ansible_user }}/docker_install.sh
  when: ansible_docker0 is undefined

- name: Give privilege
  user:
    name: "{{ ansible_user }}"
    append: yes
    groups:
      - docker

- name: install python pip on Ubuntu
  apt:
    name: python3-pip
    state: present
  when: ansible_distribution == "Ubuntu"

- name: install EPEL package on Centos7
  yum:
    name: epel-release
    state: present
  when: ansible_distribution == "Centos"

- name: install python pip on Centos
  yum:
    name: python3-pip
    state: present
  when: ansible_distribution == "Centos"

- name: install docker-py module
  pip:
    name: docker-py
    state: present

